apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bob-workspace-pvc
  labels:
    app: bob-shell
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
